# Generated by Django 4.1.7 on 2023-04-06 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_test_description_alter_test_name_alter_test_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
