# Generated by Django 4.1.7 on 2023-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_test_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='choosed_options',
            field=models.ManyToManyField(blank=True, to='account.testquestionoption'),
        ),
    ]
